modLoader="javafml"
loaderVersion="[30,)"
issueTrackerURL="https://github.com/dmillerw/Ping/issues"
logoFile="logo.png"

[[mods]]
    modId="ping"
    version="${file.jarVersion}"
    displayName="Ping"
    displayURL="https://minecraft.curseforge.com/projects/ping"
    authors="Girafi, dmillerw"
    description='''
    Inspired by Portal 2, this mod brings the Ping tool into Minecraft.
    '''

[[dependencies.ping]]
    modId="forge"
    mandatory=true
    versionRange="[30.0.17,)"
    ordering="NONE"
    side="BOTH"